Making package solver agnostic
exanauts/ProxAL.jl pull request #1
Opened 2020-09-22 17:04 UTC by michel2323

A first step in removing solvers.

2020-09-22 17:04 UTC, michel2323 commented
@AnirudhSubramanyam Am I setting the options correctly in `runtests.jl`. The tests are passed.

2020-09-22 20:20 UTC, AnirudhSubramanyam commented on src/ProxAL.jl
> +function run_proxALM(opfdata::OPFData, rawdata::RawData, optimizer;
Can we include the `optimizer` as part of AlgParams? That would probably be the right place to put that.

2020-09-22 20:25 UTC, AnirudhSubramanyam commented on src/opfblocks.jl
> +    blkOptimizer
we can probably remove this `blkOptimizer` and use the `algparams.optimizer`

2020-09-22 20:25 UTC, AnirudhSubramanyam commented on src/ProxAL.jl
> +    runinfo = ProxALMData(opfdata, rawdata, optimizer; modelinfo = modelinfo, algparams = algparams, fullmodel = true)
Can we include the `optimizer` as part of AlgParams? That would probably be the right place to put that.

2020-09-22 20:25 UTC, AnirudhSubramanyam commented on src/ProxAL.jl
> +function run_proxALM(opfdata::OPFData, rawdata::RawData, optimizer;
Can we include the `optimizer` as part of AlgParams? That would probably be the right place to put that.

2020-09-22 20:26 UTC, AnirudhSubramanyam commented on src/opfblocks.jl
> +    function OPFBlockData(opfdata::OPFData, rawdata::RawData, optimizer;
Can we include the `optimizer` as part of AlgParams? That would probably be the right place to put that.

2020-09-22 20:26 UTC, AnirudhSubramanyam commented on src/opfblocks.jl
> +    opfmodel = JuMP.Model(opfblocks.blkOptimizer)
This becomes `algparams.optimizer`

2020-09-22 20:33 UTC, AnirudhSubramanyam requested changes
Can we include `optimizer` as part of AlgParams, instead of passing it as an additional argument? That would probably be the right place to put that. Also, we can remove the `OPFBlockData.blkOptimizer` object and use the `AlgParams.optimizer` instead inside the NLP blocks.

2020-09-22 21:44 UTC, michel2323 commented
> Can we include `optimizer` as part of AlgParams, instead of passing it as an additional argument? That would probably be the right place to put that. Also, we can remove the `OPFBlockData.blkOptimizer` object and use the `AlgParams.optimizer` instead inside the NLP blocks.

That sounds good. Will get into it.

2020-10-02 16:52 UTC, michel2323 commented
@AnirudhSubramanyam  

* I put two solver fields into AlgParams.
* There are a lot of optional keyword arguments that shouldn't be optional as they can be uninitialized. I fixed most of them, but I am not sure whether this maps to your algorithm. Aka, when to switch algorithms and set their parameters.
* IMO we should merge this and continue to work both on this. I plan to work on the solver interfaces. MadNLP is currently broken due to some ambiguity in a `copy!` call, but Sungho is on it. HiOp has a whole lot of issues :-) .

2020-10-02 16:53 UTC, michel2323 commented on src/opfblocks.jl
> +    opfmodel = JuMP.Model(opfblocks.blkOptimizer)
This is addressed by the latest commit.

2020-10-02 19:12 UTC, AnirudhSubramanyam approved these changes

2020-10-02 19:12 UTC, merged