Refactoring #1
exanauts/ProxAL.jl pull request #16
Opened 2021-03-18 20:17 UTC by michel2323

I did a little refactoring inspired by Francois' work in ExaPF. Not yet all done I'd say, but feel free to leave comments.

2021-03-18 20:35 UTC, frapac requested changes
Looks good to me! 
The only thing I am not sure with is the naming: I would maybe replace `Evaluator` by `Model`, but I am open to the discussion :)

2021-03-18 20:35 UTC, frapac commented on src/Evaluators/FullModelEvaluator.jl
> +struct FullModelEvaluator <: AbstractNLPEvaluator
I would maybe rename as `FullSpaceModelEvaluator` ? Or just `FullSpaceModel`?

2021-03-18 20:35 UTC, frapac commented on src/Evaluators/FullModelEvaluator.jl
> +function FullModelEvaluator(case_file::String, load_file::String,
I would maybe try to get a more consistent indentation. Like 
```julia
function FullModelEvaluator(
    case_file::String, load_file::String,
    modelinfo::ModelParams,
    algparams::AlgParams,
    space::AbstractSpace=FullSpace(),
    comm::MPI.Comm = MPI.COMM_WORLD
)

2021-03-18 20:35 UTC, frapac commented on src/Evaluators/FullModelEvaluator.jl
> +                        time_horizon_start = 1,
Why the start of the time horizon is not an argument of the function?

2021-03-18 20:35 UTC, frapac commented on src/Evaluators/FullModelEvaluator.jl
> +    alminfo = ProxALMData(opfdata, rawdata, modelinfo, algparams, space, false)
Why do we set `false` here?

2021-03-18 20:35 UTC, frapac commented on src/Evaluators/ProxALEvalutor.jl
> +function ProxALEvaluator(case_file::String, load_file::String,
Indentation?

2021-03-18 20:35 UTC, frapac commented on src/Evaluators/ProxALEvalutor.jl
> +struct ProxALEvaluator <: AbstractNLPEvaluator
I think the meaning behind the name `ProxALEvaluator` is not straightforward to grasp

2021-03-18 20:35 UTC, frapac commented on src/Evaluators/ProxALEvalutor.jl
> +    set_rho!(algparams,
Maybe rename `set_rho!` as `set_penalty!` ?

2021-03-18 20:35 UTC, frapac commented on src/Evaluators/ProxALEvalutor.jl
> +        opt_sol[fr:to, blk] .= solution.pg[:]
I am all in to find a solution that does not depend on this explicit indexing of the vector `opt_sol`

2021-03-18 20:35 UTC, frapac commented on src/Evaluators/ProxALEvalutor.jl
> +        opt_sol[fr:to, blk] .= solution.pg[:]
(not related to this PR though)

2021-03-18 21:06 UTC, michel2323 commented on src/Evaluators/FullModelEvaluator.jl
> +struct FullModelEvaluator <: AbstractNLPEvaluator
There is also the distinction between fullspace and reduced space for the block models. But I guess that doesn't matter right?

2021-03-19 14:26 UTC, michel2323 commented on src/Evaluators/ProxALEvalutor.jl
> +struct ProxALEvaluator <: AbstractNLPEvaluator
I don't know the actual name of the method either.

2021-03-19 14:29 UTC, michel2323 commented on src/Evaluators/FullModelEvaluator.jl
> +function FullModelEvaluator(case_file::String, load_file::String,
I am not sure I know what the consistent way is :-) . Do you have a rule of thumb?

2021-03-19 14:29 UTC, michel2323 commented on src/Evaluators/ProxALEvalutor.jl
> +    set_rho!(algparams,
@AnirudhSubramanyam What do you think?

2021-03-19 14:30 UTC, michel2323 commented on src/Evaluators/ProxALEvalutor.jl
> +        opt_sol[fr:to, blk] .= solution.pg[:]
Yes. It's due to the ad-hoc MPI implementation.

2021-03-19 14:32 UTC, michel2323 commented on src/Evaluators/FullModelEvaluator.jl
> +                        time_horizon_start = 1,
I am not sure it should be an argument. @AnirudhSubramanyam What is your take? I did not see a case where this was different from 1.

2021-03-19 14:37 UTC, michel2323 commented on src/Evaluators/FullModelEvaluator.jl
> +    alminfo = ProxALMData(opfdata, rawdata, modelinfo, algparams, space, false)
I am not sure I understand what this does. If this is set to `true` it will execute this in the constructor:

2021-03-19 16:11 UTC, frapac commented on src/Evaluators/FullModelEvaluator.jl
> +function FullModelEvaluator(case_file::String, load_file::String,
I am trying to follow that guideline: https://jump.dev/JuMP.jl/v0.21.1/style/

2021-03-19 16:11 UTC, frapac commented on src/Evaluators/FullModelEvaluator.jl
> +    alminfo = ProxALMData(opfdata, rawdata, modelinfo, algparams, space, false)
I confess I don't know either...

2021-03-22 15:39 UTC, AnirudhSubramanyam commented on src/Evaluators/FullModelEvaluator.jl
> +struct FullModelEvaluator <: AbstractNLPEvaluator
@michel2323 : yes those have different meanings in ExaPF and ProxAL. I would suggest `FullSpaceModelEvaluator`

2021-03-22 15:40 UTC, AnirudhSubramanyam commented on src/Evaluators/FullModelEvaluator.jl
> +                        time_horizon_start = 1,
@frapac : good catch! @michel2323 : we don't have such a case now, but I can envision its use when we try to run this within a model predictive control application

2021-03-22 15:46 UTC, AnirudhSubramanyam commented on src/Evaluators/FullModelEvaluator.jl
> +    alminfo = ProxALMData(opfdata, rawdata, modelinfo, algparams, space, false)
@frapac @michel2323 that exists just so we can solve the full space model without decomposition, and use that as a reference solution to track convergence of the algorithm.

2021-03-22 15:47 UTC, AnirudhSubramanyam commented on src/Evaluators/ProxALEvalutor.jl
> +    set_rho!(algparams,
@michel2323 I agree with @frapac `set_penalty!` is the better name.

2021-03-22 16:05 UTC, michel2323 commented on src/Evaluators/FullModelEvaluator.jl
> +struct FullModelEvaluator <: AbstractNLPEvaluator
Fixed.

2021-03-22 16:05 UTC, michel2323 commented on src/Evaluators/FullModelEvaluator.jl
> +function FullModelEvaluator(case_file::String, load_file::String,
Fixed here and in other places.

2021-03-22 16:06 UTC, michel2323 commented on src/Evaluators/ProxALEvalutor.jl
> +struct ProxALEvaluator <: AbstractNLPEvaluator
Maybe we can solve that a later stage.

2021-03-22 16:06 UTC, michel2323 commented on src/Evaluators/ProxALEvalutor.jl
> +function ProxALEvaluator(case_file::String, load_file::String,
Fixed

2021-03-22 16:06 UTC, michel2323 commented on src/Evaluators/ProxALEvalutor.jl
> +    set_rho!(algparams,
Fixed

2021-03-22 16:12 UTC, michel2323 commented on src/Evaluators/FullModelEvaluator.jl
> +                        time_horizon_start = 1,
Fixed

2021-03-22 16:19 UTC, michel2323 commented on src/Evaluators/FullModelEvaluator.jl
> +    alminfo = ProxALMData(opfdata, rawdata, modelinfo, algparams, space, false)
Ok, I fixed this now. I think this was dead code as the constructor also solved the full model before. Now this is called explicitly with `optimize!`. I hope I didn't break anything. @frapac @AnirudhSubramanyam

2021-03-22 16:21 UTC, michel2323 commented
I addressed all your comments. Thank you! @frapac @AnirudhSubramanyam . The open comments I am either a bit unsure or they can be addressed at a later stage. Let me know if it's ready to rebase and merge.

2021-03-22 16:23 UTC, michel2323 commented on src/Evaluators/FullModelEvaluator.jl
> +    alminfo = ProxALMData(opfdata, rawdata, modelinfo, algparams, space, false)
@AnirudhSubramanyam This code was never called in the tests. The `FullSpaceEvaluator` now runs with whatever is set by the user. Should I override the algorithm parameters with `algparams.mode = :nondecomposed` and `algparams.mode = :lyapunov_bound`. Because that is now removed.

2021-03-22 16:25 UTC, AnirudhSubramanyam approved these changes

2021-03-22 16:30 UTC, AnirudhSubramanyam commented on src/Evaluators/FullModelEvaluator.jl
> +    alminfo = ProxALMData(opfdata, rawdata, modelinfo, algparams, space, false)
@michel2323 I'm not sure if we should override it. Or perhaps we give a warning before overriding it..? Even if we override, its not clear if we should go with `algparams.mode = :nondecomposed` or `algparams.mode = :lyapunov_bound`. So maybe let's just leave it as it is.

2021-03-22 22:51 UTC, frapac commented on src/Evaluators/ProxALEvalutor.jl
> +struct ProxALEvaluator <: AbstractNLPEvaluator
sounds good to me!

2021-03-22 22:52 UTC, frapac approved these changes
I think we are ready to merge this PR!

2021-03-22 22:55 UTC, michel2323 commented on src/Evaluators/FullModelEvaluator.jl
> +    alminfo = ProxALMData(opfdata, rawdata, modelinfo, algparams, space, false)
That makes sense.

2021-03-23 03:03 UTC, merged